### ISSUE TITLE
Add Disinterest

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [berengma/wildcow#11]
When using this mod, I may be inside a house (generated from the settlements mod) and these wild bulls will come after me, essentially running around the house trying to get me. I can barely get out without them attacking me. 

This seems somewhat unrealistic, I would expect them not to be so relentless, but eventually lose interest in me if they can't get me, and even quicker if they can't see me. Maybe add a limit to how long they are trying to attack someone, and make it depend on if there is a clear line of sight between the player and the bull?

**Comment by berengma** [comment]
This mod is still very wip, expect things working better in the future.

**Comment by berengma** [comment]
works for bulls now
